proxy_cert_server_dir: "{{ cert_dir }}/server"
proxy_server_cert: "{{ proxy_cert_server_dir }}/proxy_server.crt"
proxy_server_key: "{{ proxy_cert_server_dir }}/proxy_server.key"

proxy_cert_frontend_dir: "{{ cert_dir }}/frontend"
proxy_frontend_cert: "{{ proxy_cert_frontend_dir }}/proxy_frontend.crt"
proxy_frontend_key: "{{ proxy_cert_frontend_dir }}/proxy_frontend.key"

proxy_cert_backend_dir: "{{ cert_dir }}/backend"
proxy_backend_cert: "{{ proxy_cert_backend_dir }}/proxy_backend.crt"
proxy_backend_key: "{{ proxy_cert_backend_dir }}/proxy_backend.key"
