- hosts: all

  vars:
    home_dir: "/home/vagrant"
    cert_dir: "{{ home_dir }}/certs"
    pyoidc_dir: "{{ home_dir }}/pyoidc"
    op_dir: "{{ pyoidc_dir }}/oidc_example/op2"
    vopaas_dir: "{{ home_dir }}/vopaas"
    proxy_dir: "{{ vopaas_dir }}/example"
    pysaml2_dir: "{{ home_dir }}/pysaml2"
    sp_dir: "{{ pysaml2_dir }}/example/sp-wsgi"
    idp_dir: "{{ pysaml2_dir }}/example/idp2"
    pyff_dir: "{{ home_dir }}/pyff"
    pyff_metadata_dir: "{{ pyff_dir }}/metadata"
    metadata_static_dir: "{{ home_dir }}/metadata"
    metadata_dir_sp: "{{ metadata_static_dir }}/sp.xml"
    metadata_dir_idp1: "{{ metadata_static_dir }}/idp1.xml"
    metadata_dir_idp2: "{{ metadata_static_dir }}/idp2.xml"
    cm_dir: "{{ home_dir }}/CMservice"
    cm_server_dir: "{{ cm_dir }}/server"

    hostname: "hashog.umdc.umu.se"
    host: "http://{{ hostname }}"
    pyff_port: "9090"
    idp_1_port: "9088"
    idp_2_port: "9089"
    proxy_port: "8091"
    sp_port: "9087"
    op_port: "9086"
    cm_port: "9085"

    pyff_discovery_url: "{{ host }}:{{ pyff_port }}"
    cm_url: "https://{{ hostname }}:{{ cm_port }}"
    op_url: "https://{{ hostname }}"

  pre_tasks:
    - name: create directory for certs
      file: path={{ cert_dir }} state=directory owner=vagrant group=vagrant mode=0755
    - name: install apt pkg
      apt: pkg={{ item }} state=present update_cache=yes
      with_items:
        - build-essential
        - git
        - python-dev
        - libssl-dev
        - libffi-dev
        - xmlsec1
        - libxml2
        - libxslt1.1
        - libyaml-dev
        - libxml2-dev
        - libxslt1-dev
        - libxslt-dev
        - vim
        - python-setuptools
        - python-libxslt1
        - python-libxml2
        - python-pip
        - python3-pip
        - python3-tk
      sudo: Yes
    - name: fetch pysaml2 from github
      git:
        repo=https://github.com/its-dirg/pysaml2
        dest={{ pysaml2_dir }}
        version=0b1b3c7f2f92391b08c0c9b64ba2f1d6c6966dfa
        force=yes
      sudo: Yes


  roles:
    - {role: pyff, sudo: yes}
    - {role: sp, sudo: yes}
    - {role: idps, sudo: yes}
    - {role: op, sudo: yes}
    - {role: vopaas_proxy, sudo: yes}
    - {role: consent_manager, sudo: yes}
    - {role: integration_test, sudo: yes}
    - {role: metadata, sudo: yes}
    - {role: startup, sudo: yes}
