- name: fetch CMservice from github
  git:
    repo=https://github.com/its-dirg/CMservice
    dest={{ cm_dir }}
    version=07e09c1f3b8d9d86d10fc1eb2687b320a3712f5d
    force=yes

- name: Overwrite cm config
  template:
    src=settings.cfg.j2
    dest={{ cm_dir }}/server/settings.cfg

- name: Add public sign key
  copy: src=certs/vopaas_cm.pub dest={{ cm_dir }}/server/keys/sign_key.pub

- name: install requirements
  command:
    pip3 install -r {{ cm_dir }}/requirements.txt

- name: install CM from local project
  command:
    pip3 install -e .
    chdir={{ cm_dir }}

- name: Create translation files for CMService
  shell:
    nohup 3_add_translations.sh &
    chdir={{ cm_server_dir }}
