- name: Download pyff docker images
  command: docker pull leifj/pyff

- name: Creates pyff folder
  file: path={{ pyff_dir }} state=directory owner=vagrant group=vagrant mode=0755

- name: copy self-signed SSL cert
  copy: src=certs/pyff.crt dest={{ pyff_dir }}/{{ pyff_cert_file }} owner=vagrant group=vagrant mode=0755

- name: copy self-signed SSL key
  copy: src=certs/pyff.key dest={{ pyff_dir }}/{{ pyff_key_file }} owner=vagrant group=vagrant mode=0755

- name: create config.yaml
  template: src=mdx.fd.j2
            dest={{ pyff_dir }}/mdx.fd
