- name: create directory for op certs
  file: path={{ op_cert_dir }} state=directory owner=vagrant group=vagrant mode=0755
- name: copy op cert
  copy: src=certs/op.crt dest={{ op_cert }} owner=vagrant group=vagrant mode=0755
- name: copy op private key
  copy: src=certs/op.key dest={{ op_key }} owner=vagrant group=vagrant mode=0755

- name: fetch pyoidc from github
  git:
    repo=https://github.com/its-dirg/pyoidc
    dest={{ pyoidc_dir }}
    version=4ad7333d4afa0f2da82fdc761d8086a603f52597
    force=yes

- name: fetch jwkest from github
  git:
    repo=https://github.com/rohe/pyjwkest
    dest={{ home_dir }}/jwkest
    version=6928cc9c4490389b91e064422e1fe2a7ad7cf5c8
    force=yes

- name: Overwrite config.py
  template:
    src=config.py.j2
    dest={{ op_dir }}/config.py

- name: install jwkest
  command:
    pip3 install -e .
    chdir={{ home_dir }}/jwkest

#- name: install requirements
#  shell:
#    pip3 install -r {{ pyoidc_dir }}/requirements.txt

- name: install pysaml2 from local project
  command:
    pip3 install -e .
    chdir={{ pyoidc_dir }}