- name: fetch pysaml2 from github
  git:
    repo=https://github.com/rohe/pyoidc
    dest={{ pyoidc_dir }}
    version=1eaca1750233c583dec0b9ff26c08d3fdb9a5c6b
    force=yes

- name: install pip
  apt:
    name=python-pip

- name: Overwrite config.py
  template:
    src=config.py.j2
    dest={{ op_dir }}/config.py

- name: install requirements
  pip:
    requirements={{ pyoidc_dir }}/requirements.txt

- name: install pysaml2 from local project
  command:
    pip install -e .
    chdir={{ pyoidc_dir }}

- name: kill OP
  script: kill_op.sh

- name: start OP
  shell:
    nohup python server.py -p 9092 config &
    chdir={{ op_dir }}
  poll: 0