- name: Overwrite idp_1_conf.py
  template:
    src=idp_1_conf.py.j2
    dest={{ idp_dir }}/idp_1_conf.py

- name: Overwrite idp_2_conf.py
  template:
    src=idp_2_conf.py.j2
    dest={{ idp_dir }}/idp_2_conf.py

- name: install python-dev
  apt:
    name=python-dev

- name: install libldap2-dev
  apt:
    name=libldap2-dev

- name: install  libsasl2-dev
  apt:
    name=libsasl2-dev

- name: install libssl-dev
  apt:
    name=libssl-dev

- name: install python-ldap
  pip:
    name=python-ldap

