- name: Create directories
  file: path={{ item }} state=directory owner=vagrant group=vagrant mode=0755
  with_items:
    - "{{ vopaas_dir }}"
    - "{{ proxy_cert_server_dir }}"
    - "{{ proxy_cert_frontend_dir }}"
    - "{{ proxy_cert_backend_dir }}"
    - "{{ vopaas_dir }}/plugins/frontends"
    - "{{ vopaas_dir }}/plugins/backends"

- name: copy server cert
  copy: src=certs/proxy_server.crt dest={{ proxy_server_cert }} owner=vagrant group=vagrant mode=0755
- name: copy server private key
  copy: src=certs/proxy_server.key dest={{ proxy_server_key }} owner=vagrant group=vagrant mode=0755
- name: copy signing private key
  copy: src=certs/vopaas_cm.key dest={{ proxy_server_sign_key }} owner=vagrant group=vagrant mode=0755

- name: copy frontend cert
  copy: src=certs/proxy_frontend.crt dest={{ proxy_frontend_cert }} owner=vagrant group=vagrant mode=0755
- name: copy frontend private key
  copy: src=certs/proxy_frontend.key dest={{ proxy_frontend_key }} owner=vagrant group=vagrant mode=0755

- name: copy backend cert
  copy: src=certs/proxy_backend.crt dest={{ proxy_backend_cert }} owner=vagrant group=vagrant mode=0755
- name: copy backend private key
  copy: src=certs/proxy_backend.key dest={{ proxy_backend_key }} owner=vagrant group=vagrant mode=0755

- name: copy statistics private key
  copy: src=certs/vopaas_stat.key dest={{ proxy_statistics_key }} owner=vagrant group=vagrant mode=0755




- name: fetch VOPaaS from github
  git:
    repo=https://github.com/its-dirg/VOPaaS
    dest={{ vopaas_src_dir }}
    version=5d96c0011a7f155645636a8b2fea3dd62018a46b
    force=yes

- name: install requirements
  command:
    pip3 install -r {{ vopaas_src_dir }}/requirements.txt

- name: install cryptography
  command:
    pip3 install cryptography

- name: install pycrypto
  command:
    pip3 install pycrypto

- name: install PyYAML
  command:
    pip3 install PyYAML

- name: Overwrite internal_attributes.yaml
  template:
    src=internal_attributes.yaml.j2
    dest={{ vopaas_dir }}/internal_attributes.yaml

- name: Overwrite proxy_conf.yaml
  template:
    src=proxy_conf.yaml.j2
    dest={{ vopaas_dir }}/proxy_conf.yaml

- name: Overwrite saml2_backend.yaml
  template:
    src=saml2_backend.yaml.j2
    dest={{ vopaas_dir }}/plugins/backends/saml2_backend.yaml

- name: Overwrite saml2_frontend.yaml
  template:
    src=saml2_frontend.yaml.j2
    dest={{ vopaas_dir }}/plugins/frontends/saml2_frontend.yaml

- name: Creates "micro_services" directory
  file: path={{ vopaas_dir }}/plugins/micro_services state=directory

- name: Overwrite statistics_service.yaml
  template:
    src=statistics_service.yaml.j2
    dest={{ vopaas_dir }}/plugins/micro_services/statistics_service.yaml

- name: Overwrite op backend
  template:
    src=openid_backend.yaml.j2
    dest={{ vopaas_dir }}/plugins/backends/openid_backend.yaml

- name: install vopaas from local project
  command:
    pip3 install -e .
    chdir={{ vopaas_src_dir }}
