- name: create directory for server certs
  file: path={{ proxy_cert_server_dir }} state=directory owner=vagrant group=vagrant mode=0755
- name: copy server cert
  copy: src=localhost.crt dest={{ proxy_server_cert }} owner=vagrant group=vagrant mode=0755
- name: copy server private key
  copy: src=localhost.key dest={{ proxy_server_key }} owner=vagrant group=vagrant mode=0755

- name: create directory for frontend certs
  file: path={{ proxy_cert_frontend_dir }} state=directory owner=vagrant group=vagrant mode=0755
- name: copy frontend cert
  copy: src=localhost.crt dest={{ proxy_frontend_cert }} owner=vagrant group=vagrant mode=0755
- name: copy frontend private key
  copy: src=localhost.key dest={{ proxy_frontend_key }} owner=vagrant group=vagrant mode=0755

- name: create directory for backend certs
  file: path={{ proxy_cert_backend_dir }} state=directory owner=vagrant group=vagrant mode=0755
- name: copy backend cert
  copy: src=localhost.crt dest={{ proxy_backend_cert }} owner=vagrant group=vagrant mode=0755
- name: copy backend private key
  copy: src=localhost.key dest={{ proxy_backend_key }} owner=vagrant group=vagrant mode=0755

- name: fetch VOPaaS from github
  git:
    repo=https://github.com/its-dirg/VOPaaS
    dest={{ vopaas_dir }}
    force=yes

- name: install python3-pip
  apt:
    name=python3-pip

- name: install example requirements
  command:
    pip3 install -r {{ vopaas_dir }}/requirements.txt

- name: install cryptography
  command:
    pip3 install cryptography

- name: install pycrypto
  command:
    pip3 install pycrypto

- name: install PyYAML
  command:
    pip3 install PyYAML

- name: install python3-tk
  apt:
    name=python3-tk

- name: install pysaml
  command:
    pip3 install git+https://github.com/rohe/pysaml2

- name: Overwrite proxy_conf.yaml
  template:
    src=proxy_conf.yaml.j2
    dest={{ proxy_dir }}/proxy_conf.yaml

- name: Overwrite saml2_backend.py
  template:
    src=saml2_backend.py.j2
    dest={{ proxy_dir }}/plugins/backends/saml2_backend.py

- name: Overwrite saml2_frontend.py
  template:
    src=saml2_frontend.py.j2
    dest={{ proxy_dir }}/plugins/frontends/saml2_frontend.py

- name: install example requirements
  command:
    pip3 install -r {{ vopaas_dir }}/requirements.txt

- name: install saas from local project
  command:
    pip3 install -e .
    chdir={{ vopaas_dir }}
