- name: Killing pyff
  action: shell pkill -KILL pyffd
  ignore_errors: True

- name: Killing all python and python3 processes
  action: shell pkill -KILL python
  ignore_errors: True

- name: Killing manually processes started with sudo
  action: shell pkill -KILL sudo
  ignore_errors: True

- name: Create wait_for_pyff script
  template:
    src=wait_for_pyff.sh
    dest={{ home_dir }}/wait_for_pyff.sh
    mode=0755

- name: start pyff
  shell:
    pyffd -P {{ pyff_port }} --loglevel=DEBUG --log={{ pyff_dir }}/pyff.log -H 0.0.0.0 --dir={{ pyff_dir }} mdx.fd
    chdir={{ pyff_dir }}

- name: wait for pyff
  shell:
    ./wait_for_pyff.sh
    chdir={{ home_dir }}

- name: starting IDP 1
  shell:
    nohup python idp.py idp_1_conf &
    chdir={{ idp_dir }}
  poll: 0

- name: starting IDP 2
  shell:
    nohup python idp.py idp_2_conf &
    chdir={{ idp_dir }}
  poll: 0

- name: start SP
  shell:
    nohup python sp.py -D {{ pyff_discovery_url }}/role/idp.ds sp_conf &
    chdir={{ sp_dir }}
  poll: 0

- name: start OP
  shell:
    nohup python3 server.py -p {{ op_port }} config &
    chdir={{ op_dir }}
  poll: 0

- name: Start CMService
  shell:
    nohup python3 flask_server.py &
    chdir={{ cm_server_dir }}

- name: Start ALService
  shell:
    nohup python3 flask_server.py &
    chdir={{ al_server_dir }}

- name: start proxy
  shell:
    nohup python3 {{ vopaas_src_dir }}/src/vopaas/vopaas_server.py proxy_conf.yaml &
    chdir={{ vopaas_dir }}
  poll: 0