- name: Killing pyff
  action: shell pkill -f pyffd
  ignore_errors: True

- name: Create wait_for_pyff script
  template:
    src=wait_for_pyff.sh
    dest={{ home_dir }}/wait_for_pyff.sh
    mode=0755

- name: start pyff
  shell:
    pyffd -P {{ pyff_port }} --loglevel=DEBUG --log={{ pyff_dir }}/pyff.log -H 0.0.0.0 --dir={{ pyff_dir }} mdx.fd
    chdir={{ pyff_dir }}

- name: wait for pyff
  shell:
    ./wait_for_pyff.sh
    chdir={{ home_dir }}

- name: kill idps
  script: kill_idps.sh

- name: starting IDP 1
  shell:
    nohup python idp.py idp_1_conf &
    chdir={{ idp_dir }}
  poll: 0

- name: starting IDP 2
  shell:
    nohup python idp.py idp_2_conf &
    chdir={{ idp_dir }}
  poll: 0

- name: kill sp
  script: kill_sp.sh

- name: start SP
  shell:
    nohup python sp.py -D {{ pyff_discovery_url }}/role/idp.ds sp_conf &
    chdir={{ sp_dir }}
  poll: 0

- name: kill OP
  script: kill_op.sh

- name: start OP
  shell:
    nohup python3 server.py -p {{ op_port }} config &
    chdir={{ op_dir }}
  poll: 0

- name: Kill CMservice
  action: shell pkill flask_server
  ignore_errors: True

- name: Start CMService
  shell:
    nohup python3 flask_server.py
    chdir={{ cm_dir }}

- name: Kill proxy
  script: kill_proxy.sh

- name: start proxy
  shell:
    nohup python3 proxy_server.py proxy_conf.yaml &
    chdir={{ proxy_dir }}
  poll: 0