- name: Overwrite sp_conf.py
  template:
    src=sp_conf.py.j2
    dest={{ sp_dir }}/sp_conf.py
    force=yes

- name: Overwrite sp_2_conf.py
  template:
    src=sp_2_conf.py.j2
    dest={{ sp_dir }}/sp_2_conf.py
    force=yes

- name: Overwrite service_conf.py
  template:
    src=service_conf.py.j2
    dest={{ sp_dir }}/service_conf.py
    force=yes

- name: Overwrite service_2_conf.py
  template:
    src=service_2_conf.py.j2
    dest={{ sp_dir }}/service_2_conf.py
    force=yes

- name: install cryptography
  pip:
    name=cryptography

- name: install pycrypto
  pip:
    name=pycrypto

- name: install PyYAML
  pip:
    name=PyYAML

- name: install example requirements
  pip:
    requirements={{ pysaml2_dir }}/example/requirements.txt

- name: install pysaml2 from local project
  command:
    pip install -e .
    chdir={{ pysaml2_dir }}
