- name: fetch pysaml2 from github
  git:
    repo=https://github.com/its-dirg/pysaml2
    dest={{ pysaml2_dir }}
    version=a001e0e7a3b9824096e284e409b8880bb83d4c5e
    force=yes

- name: install pip
  apt:
    name=python-pip

- name: Overwrite sp_conf.py
  template:
    src=sp_conf.py.j2
    dest={{ sp_dir }}/sp_conf.py

- name: Overwrite service_conf.py
  template:
    src=service_conf.py.j2
    dest={{ sp_dir }}/service_conf.py

- name: install cryptography
  pip:
    name=cryptography

- name: install pycrypto
  pip:
    name=pycrypto

- name: install PyYAML
  pip:
    name=PyYAML

- name: install example requirements
  pip:
    requirements={{ pysaml2_dir }}/example/requirements.txt

- name: install pysaml2 from local project
  command:
    pip install -e .
    chdir={{ pysaml2_dir }}
