- name: fetch pysaml2 from github
  git:
    repo=https://github.com/its-dirg/pysaml2
    dest={{ pysaml2_dir }}
    version=014d7e2d4bc5d6b749a306cf6716739771c3c988
    force=yes

- name: Overwrite sp_conf.py
  template:
    src=sp_conf.py.j2
    dest={{ sp_dir }}/sp_conf.py
    force=yes

- name: Overwrite service_conf.py
  template:
    src=service_conf.py.j2
    dest={{ sp_dir }}/service_conf.py
    force=yes

- name: install cryptography
  pip:
    name=cryptography

- name: install pycrypto
  pip:
    name=pycrypto

- name: install PyYAML
  pip:
    name=PyYAML

- name: install example requirements
  pip:
    requirements={{ pysaml2_dir }}/example/requirements.txt

- name: install pysaml2 from local project
  command:
    pip install -e .
    chdir={{ pysaml2_dir }}
